import {
  IoAddOutline,
  IoAlertCircleOutline,
  IoAnalytics,
  IoAnalyticsOutline,
  IoAppsOutline,
  IoArrowBack,
  IoBarChartOutline,
  IoBarcodeOutline,
  IoBook,
  IoBusinessOutline,
  IoCalendar,
  IoCalendarClearOutline,
  IoCalendarOutline,
  IoCallOutline,
  IoCheckmark,
  IoCheckmarkCircle,
  IoChevronBack,
  IoChevronDown,
  IoChevronForward,
  IoChevronUp,
  IoClose,
  IoCloseCircle,
  IoCloseOutline,
  IoCloudOfflineOutline,
  IoCompassOutline,
  IoDocumentText,
  IoDocumentTextOutline,
  IoDownloadOutline,
  IoEllipsisVertical,
  IoEye,
  IoEyeOff,
  IoFileTrayOutline,
  IoFilterOutline,
  IoFingerPrintOutline,
  IoGridOutline,
  IoHelpCircleOutline,
  IoHome,
  IoIdCardOutline,
  IoInformationCircleOutline,
  IoLibraryOutline,
  IoLocationOutline,
  IoLockClosedOutline,
  IoLogOutOutline,
  IoLogoWhatsapp,
  IoMegaphone,
  IoMenuOutline,
  IoNotificationsOutline,
  IoOpenOutline,
  IoPeopleOutline,
  IoPerson,
  IoPlay,
  IoPower,
  IoRefresh,
  IoRibbonOutline,
  IoSchool,
  IoSearchOutline,
  IoSettingsOutline,
  IoShareOutline,
  IoStatsChart,
  IoSyncCircle,
  IoTime,
  IoTimeOutline,
  IoWarningOutline,
} from 'react-icons/io5'

// Maps Ionicons kebab-case names (as used throughout the RN app via
// @expo/vector-icons' <Ionicons name="..." />) to the matching react-icons
// Ionicons5 component. Explicit map (rather than a wildcard `import *`) so
// the production bundle only ships the ~50 glyphs this app actually uses.
const ICONS = {
  'add-outline': IoAddOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  analytics: IoAnalytics,
  'analytics-outline': IoAnalyticsOutline,
  'apps-outline': IoAppsOutline,
  'arrow-back': IoArrowBack,
  'bar-chart-outline': IoBarChartOutline,
  'barcode-outline': IoBarcodeOutline,
  book: IoBook,
  'business-outline': IoBusinessOutline,
  calendar: IoCalendar,
  'calendar-clear-outline': IoCalendarClearOutline,
  'calendar-outline': IoCalendarOutline,
  'call-outline': IoCallOutline,
  checkmark: IoCheckmark,
  'checkmark-circle': IoCheckmarkCircle,
  'chevron-back': IoChevronBack,
  'chevron-down': IoChevronDown,
  'chevron-forward': IoChevronForward,
  'chevron-up': IoChevronUp,
  close: IoClose,
  'close-circle': IoCloseCircle,
  'close-outline': IoCloseOutline,
  'cloud-offline-outline': IoCloudOfflineOutline,
  'compass-outline': IoCompassOutline,
  'document-text': IoDocumentText,
  'document-text-outline': IoDocumentTextOutline,
  'download-outline': IoDownloadOutline,
  'ellipsis-vertical': IoEllipsisVertical,
  eye: IoEye,
  'eye-off': IoEyeOff,
  'file-tray-outline': IoFileTrayOutline,
  'filter-outline': IoFilterOutline,
  'finger-print-outline': IoFingerPrintOutline,
  'grid-outline': IoGridOutline,
  'help-circle-outline': IoHelpCircleOutline,
  home: IoHome,
  'id-card-outline': IoIdCardOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'library-outline': IoLibraryOutline,
  'location-outline': IoLocationOutline,
  'lock-closed-outline': IoLockClosedOutline,
  'log-out-outline': IoLogOutOutline,
  'logo-whatsapp': IoLogoWhatsapp,
  megaphone: IoMegaphone,
  'menu-outline': IoMenuOutline,
  'notifications-outline': IoNotificationsOutline,
  'open-outline': IoOpenOutline,
  'people-outline': IoPeopleOutline,
  person: IoPerson,
  play: IoPlay,
  power: IoPower,
  refresh: IoRefresh,
  'ribbon-outline': IoRibbonOutline,
  school: IoSchool,
  'search-outline': IoSearchOutline,
  'settings-outline': IoSettingsOutline,
  'share-outline': IoShareOutline,
  'stats-chart': IoStatsChart,
  'sync-circle': IoSyncCircle,
  time: IoTime,
  'time-outline': IoTimeOutline,
  'warning-outline': IoWarningOutline,
}

export default function Icon({ name, size = 20, color = 'currentColor', className = '', style }) {
  const Component = ICONS[name]

  if (!Component) {
    if (import.meta.env.DEV) {
      console.warn(`Icon: no mapping for "${name}" — add it to src/components/Icon.jsx`)
    }
    return null
  }

  return <Component size={size} color={color} className={className} style={style} />
}
